version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: "daily"
    registries:
      - github

registries:
  github:
    type: git
    url: https://github.com
    username: x-access-token
    password: ${{secrets.GH_PERSONAL_TOKEN}}

